@APi_HostAddress = https://localhost:7161

GET {{APi_HostAddress}}/weatherforecast/
Accept: application/json

###
###---------------Auth------------------------------


POST {{APi_HostAddress}}/api/auth/logout

###

POST {{APi_HostAddress}}/api/auth/Login
Content-Type: application/json

{
  //LoginRequestDTO
}

###

GET {{APi_HostAddress}}/api/auth/profile

###

GET {{APi_HostAddress}}/api/Auth/profile

###

POST {{APi_HostAddress}}/api/auth/refresh-token
Content-Type: application/json

{
  //RefreshTokenRequest
}

###

POST {{APi_HostAddress}}/api/auth/register
Content-Type: application/json

{
  //RegisterRequestDTO
}

###

POST {{APi_HostAddress}}/api/auth/revoke-token
Content-Type: application/json

{
  //RefreshTokenRequest
}

###

GET {{APi_HostAddress}}/api/auth/TestConnect

###
###---------------Auth------------------------------

